### ISSUE TITLE
up metric

### ISSUE THREAD

**Issue by rafaelpirolla** [citrix/citrix-adc-metrics-exporter#39]
As per:
https://prometheus.io/docs/instrumenting/writing_exporters/#failed-scrapes

It's good practice to create the up metric for the exporter like in:
https://github.com/prometheus/haproxy_exporter/blob/146b612c9e13960a8c9adf0e98f50a6ad7e96e1f/haproxy_exporter.go#L321

Although it seems we have it on citrix_exporter it never seems to go to 0.

It would be great to have it set to 0 when the ADC fetch is not successful.

**Comment by aroraharsh23** [comment]
I am not sure of what's the requirement here.  
So, when we say scrape failed : Is this for a particular metric or like the entire failed scrape?
Also, they have also mentioned 
"although you can’t distinguish between the exporter being down and the application being down" 
Won't it create confusion to begin with?

**Comment by rafaelpirolla** [comment]
So, when we say scrape failed : Is this for a particular metric or like the entire failed scrape?
- When the entire scrape fails (e.g. adc is down)

For citrix-exporter as of now it's a bit hard to create an alert to tell that the ADC is down.

**Comment by aroraharsh23** [comment]
Thanks.
Will explore the feasibility and implications of adding this.

**Comment by aroraharsh23** [comment]
Rafael,
When you say "Although it seems we have it on citrix_exporter it never seems to go to 0."

Are you referring to process stats or something else, can you share an example for which stat you were referring to.
I am assuming you refer to process_* stat should also go to zero. Is the understanding correct?

**Comment by rafaelpirolla** [comment]
I meant the up metric.

**Comment by rafaelpirolla** [comment]
Say you have this docker-compose.yml:
```
version: '3.4'

services:
  cpx:
    container_name: cpx
    image: quay.io/citrix/citrix-k8s-cpx-ingress:12.1-51.16
    ports:
      - 9080:9080
      - 8000:8000
    tty: true
    ulimits:
      core: -1
    environment:
      "CPX_CORES": 2
      EULA: "yes"
    privileged: true
    networks:
      - monitoring

  citrix_exporter:
    container_name: citrix_exporter
    image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.6
    volumes:
      - ./citrix_exporter:/citrix_exporter
    command: --target-nsip cpx:9080 --port 9090 --config-file /citrix_exporter/config.yaml --secure no --metrics-file /citrix_exporter/metrics.json
    ports:
      - 9090:9090
    networks:
      - monitoring

networks:
  monitoring:
```
The metrics.json file is just getting one metric: 
```
{
    "system": {
        "gauges": [
            ["cpuusagepcnt", "adc_cpu_usage_percent"]
        ]
    }
}
```
And config is setting nsroot, nsroot for pass as per this CPX version.

Then you can get the stats from CPX: 
```
~ ❯❯❯ curl -s localhost:9090/metrics | grep -v "^#"
python_gc_objects_collected_total{generation="0"} 514.0
python_gc_objects_collected_total{generation="1"} 7.0
python_gc_objects_collected_total{generation="2"} 0.0
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
python_gc_collections_total{generation="0"} 60.0
python_gc_collections_total{generation="1"} 5.0
python_gc_collections_total{generation="2"} 0.0
python_info{implementation="CPython",major="3",minor="8",patchlevel="2",version="3.8.2"} 1.0
process_virtual_memory_bytes 2.8082176e+07
process_resident_memory_bytes 2.2921216e+07
process_start_time_seconds 1.60491923329e+09
process_cpu_seconds_total 0.37
process_open_fds 7.0
process_max_fds 1.048576e+06
adc_cpu_usage_percent{nsip="cpx:9080"} 0.0
```
Now we stop CPX:
```
~ ❯❯❯ docker stop cpx
cpx
```
And finally get the stats again:
```
~ ❯❯❯ curl -s localhost:9090/metrics | grep -v "^#"
python_gc_objects_collected_total{generation="0"} 514.0
python_gc_objects_collected_total{generation="1"} 7.0
python_gc_objects_collected_total{generation="2"} 0.0
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
python_gc_collections_total{generation="0"} 60.0
python_gc_collections_total{generation="1"} 5.0
python_gc_collections_total{generation="2"} 0.0
python_info{implementation="CPython",major="3",minor="8",patchlevel="2",version="3.8.2"} 1.0
process_virtual_memory_bytes 2.8082176e+07
process_resident_memory_bytes 2.3048192e+07
process_start_time_seconds 1.60491923329e+09
process_cpu_seconds_total 0.39999999999999997
process_open_fds 8.0
process_max_fds 1.048576e+06
```

How can anyone tell by any of these metrics that the exporter is up and the CPX is down?
